"""
Metrics constants for the multi-AMR warehouse coordination simulator.
Reference doc Section 16.2.
"""

MAKESPAN = "MAKESPAN"
SUM_COMPLETION_TIME = "SUM_COMPLETION_TIME"
AVG_TASK_COMPLETION_TIME = "AVG_TASK_COMPLETION_TIME"
WAITING_TIME = "WAITING_TIME"
COLLISION_COUNT = "COLLISION_COUNT"
DEADLOCK_COUNT = "DEADLOCK_COUNT"
REPLAN_COUNT = "REPLAN_COUNT"
THROUGHPUT = "THROUGHPUT"
COMM_LATENCY = "COMM_LATENCY"
MESSAGE_LOSS = "MESSAGE_LOSS"
CPU_MEMORY = "CPU_MEMORY"
EDGE_INFERENCE_LATENCY = "EDGE_INFERENCE_LATENCY"
ENERGY_PROXY = "ENERGY_PROXY"
